---
title: "Untitled"
output: html_document
date: "2025-09-05"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

images <- loadImages("/mnt/central_nas/projects/Pladioc/SRIMC_project/Zenodo/Extended_Data_2/images_SNR/")

```

```{r signal to noise ratio}

channelNames(images) <- c("Xe", "GLUT1", "SMA", "DNA1", "DNA2")

# Store patient and image level information in elementMetadata
mcols(images) <- DataFrame(image = names(images))

cur <- lapply(names(images), function(x){
    img <- images[[x]]
    mat <- apply(img, 3, function(ch){
        # Otsu threshold
        thres <- otsu(ch, range = c(min(ch), max(ch)), levels = 65536)

        snr <- mean(ch[ch > thres]) / mean(ch[ch <= thres])
        ps <- mean(ch[ch > thres])
        ts <- sum(ch[ch > thres])
        
        return(c(snr = snr, ps = ps, ts = ts))
    })
    t(mat) %>% as.data.frame() %>% 
        mutate(image = x,
               marker = colnames(mat)) %>% 
        pivot_longer(cols = c(snr, ps, ts))
})

cur_snr <- do.call(rbind, cur)
cur_snr <- cur_snr[which(!cur_snr$marker %in% c("Xe", "DNA1", "DNA2")),]
cur_snr$condition <- rep(c(rep("after",6), rep("before",6)),10)
cur_snr$marker <- c(rep(c(rep("GLUT1",3), rep("SMA",3)),10), rep(c(rep("Vimentin",3), rep("ATP5A",3)),10))
cur_snr$tissue <- c(rep("colon",12), rep("kidney",12), rep("LUAD",12), rep("lung",12), rep("placenta",12),
                    rep("colon",12), rep("kidney",12), rep("LUAD",12), rep("lung",12), rep("placenta",12))


ggplot(cur_snr[which(cur_snr$marker == "GLUT1" & cur_snr$name == "snr"),], 
       aes(x = factor(condition, levels = c("before", "after")), y = (value))) +
  geom_boxplot(fill = alpha("darkturquoise", 0.2), col = "darkturquoise") +
  ylab("SNR") +
  geom_point(aes(col = tissue), size = 3, alpha = 0.7) +
  scale_color_manual(values = c("black", "grey30", "grey50", "grey70", "grey85")) +
  geom_line(aes(group = tissue), size = 0.3, col = "grey") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        panel.grid = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, size = 0.5),
        panel.background = element_rect(fill = "white")) 

ggplot(cur_snr[which(cur_snr$marker == "SMA" & cur_snr$name == "snr"),], 
       aes(x = factor(condition, levels = c("before", "after")), y = (value))) +
  geom_boxplot(fill = alpha("red", 0.2), col = "red") +
  ylab("SNR") +
  geom_point(aes(col = tissue), size = 3, alpha = 0.7) +
  scale_color_manual(values = c("black", "grey30", "grey50", "grey70", "grey85")) +
  geom_line(aes(group = tissue), size = 0.3, col = "grey") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        panel.grid = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, size = 0.5),
        panel.background = element_rect(fill = "white")) 

ggplot(cur_snr[which(cur_snr$marker == "Vimentin" & cur_snr$name == "snr"),], 
       aes(x = factor(condition, levels = c("before", "after")), y = (value))) +
  geom_boxplot(fill = alpha("cornflowerblue", 0.2), col = "cornflowerblue") +
  ylab("SNR") +
  geom_point(aes(col = tissue), size = 3, alpha = 0.7) +
  scale_color_manual(values = c("black", "grey30", "grey50", "grey70", "grey85")) +
  geom_line(aes(group = tissue), size = 0.3, col = "grey") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        panel.grid = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, size = 0.5),
        panel.background = element_rect(fill = "white")) 

ggplot(cur_snr[which(cur_snr$marker == "ATP5A" & cur_snr$name == "snr"),], 
       aes(x = factor(condition, levels = c("before", "after")), y = (value))) +
  geom_boxplot(fill = alpha("darkorange", 0.2), col = "darkorange") +
  ylab("SNR") +
  geom_point(aes(col = tissue), size = 3, alpha = 0.7) +
  scale_color_manual(values = c("black", "grey30", "grey50", "grey70", "grey85")) +
  geom_line(aes(group = tissue), size = 0.3, col = "grey") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        panel.grid = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, size = 0.5),
        panel.background = element_rect(fill = "white")) 

t.test(cur_snr$value[which(cur_snr$name == "snr" & cur_snr$condition == "before" & cur_snr$marker == "GLUT1")], 
       cur_snr$value[which(cur_snr$name == "snr" & cur_snr$condition == "after" & cur_snr$marker == "GLUT1")], paired = TRUE)
t.test(cur_snr$value[which(cur_snr$name == "snr" & cur_snr$condition == "before" & cur_snr$marker == "SMA")], 
       cur_snr$value[which(cur_snr$name == "snr" & cur_snr$condition == "after" & cur_snr$marker == "SMA")], paired = TRUE)
t.test(cur_snr$value[which(cur_snr$name == "snr" & cur_snr$condition == "before" & cur_snr$marker == "Vimentin")], 
       cur_snr$value[which(cur_snr$name == "snr" & cur_snr$condition == "after" & cur_snr$marker == "Vimentin")], paired = TRUE)
t.test(cur_snr$value[which(cur_snr$name == "snr" & cur_snr$condition == "before" & cur_snr$marker == "ATP5A")], 
       cur_snr$value[which(cur_snr$name == "snr" & cur_snr$condition == "after" & cur_snr$marker == "ATP5A")], paired = TRUE)

```