---
title: "Tige_Lilly_500"
author: "James Whipman"
date: "2025-04-29"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(EBImage)
library(reshape2)
library(ggplot2)
library(dplyr)
library(tidyr)
library(purrr)
library(ggrepel)
library(cytomapper)
```


## Plotting the signal loss and SNR for TigerLilly intrument
```{r read in the repetition data}
list <- list.files("/mnt/central_nas/projects/Pladioc/SRIMC_project/Zenodo/Extended_Data_3/IMC_system_comparison/img_dB/")
all_channels <- lapply(list,function(x) readImage(paste0("/mnt/central_nas/projects/Pladioc/SRIMC_project/Zenodo/Extended_Data_3/IMC_system_comparison/img_dB/", x)))
```

```{r extract intensities}

intensities <- vapply(all_channels, function(x) sum(imageData(x)[,,33]), numeric(1))
data <- data.frame(c(intensities[22:26]),
                   c(intensities[c(16,18:21)]),
                   c(intensities[1:5]),
                   c(intensities[6:10]),
                   c(intensities[11:15]))

data <- t(data)
rownames(data) <-c(4,0,-1,-2,-4)
colnames(data) <- 1:5
data <- melt(data)
colnames(data) <- c("dB", "pass", "Intensity")
data$dB <- as.factor(data$dB)
```


```{r}
to_plot <- data

ggplot(to_plot, aes(x = pass, y = Intensity, col = dB, fill = dB)) +
  geom_point(shape=21, color="black", size = 3, alpha = 0.7) +
  geom_smooth(data = to_plot[which(to_plot$dB %in% c("-4")),],
              method = "nls", 
              formula = y ~ I0 / (1 + exp(0.4*(x - x0))), 
              method.args = list(start = list(I0 = max(to_plot$Intensity), x0 = median(to_plot$pass))),
              se = FALSE) +
  geom_smooth(data = to_plot[which(to_plot$dB %in% c("-2")),],
              method = "nls", 
              formula = y ~ I0 / (1 + exp(1.1*(x - x0))), 
              method.args = list(start = list(I0 = max(to_plot$Intensity), x0 = median(to_plot$pass))),
              se = FALSE) +
  geom_smooth(data = to_plot[which(to_plot$dB %in% c("-1")),],
              method = "nls", 
              formula = y ~ I0 / (1 + exp(1.8*(x - x0))), 
              method.args = list(start = list(I0 = max(to_plot$Intensity), x0 = median(to_plot$pass))),
              se = FALSE) +
  geom_smooth(data = to_plot[which(to_plot$dB %in% c("0")),],
              method = "nls", 
              formula = y ~ I0 / (1 + exp(2.5*(x - x0))), 
              method.args = list(start = list(I0 = max(to_plot$Intensity), x0 = median(to_plot$pass))),
              se = FALSE) +
  geom_smooth(data = to_plot[which(to_plot$dB %in% c("4")),],
              method = "nls", 
              formula = y ~ I0 / (1 + exp(2.9*(x - x0))), 
              method.args = list(start = list(I0 = max(to_plot$Intensity), x0 = median(to_plot$pass))),
              se = FALSE) +
  scale_fill_manual(values = c("grey70", "#F5B35E", "#EA7246", "#DD708E", "#33608C")) +
  scale_color_manual(values = c("grey70", "#F5B35E", "#EA7246", "#DD708E", "#33608C")) +
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1),
        panel.background = element_blank(),
        panel.grid.minor = element_line(colour="grey95", size=0.5),
        text = element_text(size = 15))

```


```{r SNR}
images <- loadImages("/mnt/central_nas/projects/Pladioc/SRIMC_project/Zenodo/Extended_Data_3/IMC_system_comparison/img_SNR/")
panel <- read.csv("/mnt/central_nas/projects/Pladioc/SRIMC_project/Zenodo/Extended_Data_3/IMC_system_comparison/panel.csv")
channelNames(images) <- panel$name
mcols(images) <- DataFrame(image = names(images))
working_panel <- panel[-c(3:4,6,9,14,18:19,26:28,31,35:40),]


cur <- lapply(names(images), function(x){
    img <- images[[x]]
    mat <- apply(img, 3, function(ch){
        # Otsu threshold
        thres <- otsu(ch, range = c(min(ch), max(ch)), levels = 65536)

        snr <- mean(ch[ch > thres]) / mean(ch[ch <= thres])
        ps <- mean(ch[ch > thres])
        ts <- sum(ch[ch > thres])
        
        return(c(snr = snr, ps = ps, ts = ts))
    })
    t(mat) %>% as.data.frame() %>% 
        mutate(image = x,
               marker = colnames(mat)) %>% 
        pivot_longer(cols = c(snr, ps, ts))
})

cur_snr <- do.call(rbind, cur)
cur_snr$resolution <- c(rep("HR-IMC Hyperion+", 102), rep("Classic IMC Hyperion+", 102), rep("Classic IMC Hyperion Xti", 102), rep("HR-IMC Hyperion Xti", 102))

data <- cur_snr %>% 
    pivot_wider(names_from = name, values_from = value) %>%
    dplyr::filter(ps > 2) %>%
    pivot_longer(cols = c(snr, ps))

data <- data %>% 
    dplyr::group_by(marker, name, resolution) %>%
    dplyr::summarize(log_mean = log2(mean(value))) %>%
    pivot_wider(names_from = name, values_from = log_mean)


data <- as.data.frame(data)
data <- data[which(data$marker %in% working_panel$name),]
data$marker <- sub("^[^_]*_", "", data$marker)
markers <- data$marker

input <- data[which(data$marker %in% markers),]
input$resolution <- factor(input$resolution)

ggplot(input, aes(ps, snr)) +
    geom_point(aes(ps, snr, col = resolution)) +
    geom_label_repel(data = subset(input, marker %in% c("SMA", "CD11b", "FoxP3")), aes(ps, snr, label = marker, col = resolution)) +
  scale_color_manual(values = c("#33608C", "#76669B", "#DD708E", "#F5B35E")) +
    ylab("Signal-to-noise ratio [log2]") +
    xlab("Signal intensity [log2]") +
  xlim(c(0,12)) +
  ylim(c(0.5,9)) +
  #geom_encircle(data = subset(input, resolution == "Classic IMC Hyperion Xti"), color = NA, fill = alpha("#33608C", 0.1),
                #s_shape = 0.5) +
  #geom_encircle(data = subset(input, resolution == "Classic IMC Hyperion+"), color = NA, fill = alpha("#76669B", 0.1),
                #s_shape = 0.5) +
  #geom_encircle(data = subset(input, resolution == "HR-IMC Hyperion Xti"), color = NA, fill = alpha("#DD708E", 0.1),
                #s_shape = 0.5) +
  #geom_encircle(data = subset(input, resolution == "HR-IMC Hyperion+"), color = NA, fill = alpha("#F5B35E", 0.1),
                #s_shape = 0.5) +
  theme(panel.grid = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, size = 1),
        panel.background = element_rect(fill = "white")) 

```


