---
title: "Untitled"
output: html_document
date: "2025-04-15"
editor_options: 
  chunk_output_type: console
---

```{r}
library(EBImage)
library(reshape2)
library(imcRtools)
library(SingleCellExperiment)
library(mclust)
library(cytomapper)
library(BayesSpace)
library(CATALYST)
library(cytoviewer)
```


```{r}
path_to_image <- "/mnt/central_nas/projects/Pladioc/SRIMC_project/Zenodo/Figure_4/img/"
path_to_masks <- "/mnt/central_nas/projects/Pladioc/SRIMC_project/Zenodo/Figure_4/masks/"
panel <- read.csv(file = "/mnt/central_nas/projects/Pladioc/SRIMC_project/Zenodo/Figure_4/panel.csv", stringsAsFactors = FALSE)
spillover <- read.csv("/mnt/central_nas/projects/Pladioc/SRIMC_project/Zenodo/Figure_4/spillover.csv", row.names = 1)
```


```{r}
images <- list.files(path_to_image)
images <- images[1:3]
masks_files <- list.files(path_to_masks)

sce_objects <- lapply(1:length(images), function(x) {
  image_ECM <- EBImage::readImage(paste0(path_to_image, images[x]), all = TRUE, type = "tiff")
  masks <- EBImage::readImage(paste0(path_to_masks, masks_files[x]))
  mask_indices <- which(imageData(masks) != 0, arr.ind = TRUE)
  cells <- imageData(masks)[mask_indices]
  cellno <- setNames(1:length(unique(cells)), unique(cells))
  renamed <- cellno[as.character(cells)]

  channel_data <- lapply(1:dim(image_ECM)[3], function(x) imageData(image_ECM)[,,x][mask_indices])
  counts <- as.data.frame(channel_data)
  colnames(counts) <- panel$name <- gsub("^[^_]*_", "", panel$name)
  coords <- as.data.frame(mask_indices)

  sce <- SingleCellExperiment(assays = list(counts = t(counts)))
  sce$Center_X <- coords[,1]
  sce$Center_Y <- coords[,2]
  sce$image <- gsub("\\.tiff$", "", images[x])
  sce$cell <- paste0(renamed, "_", as.character(x))
  return(sce)
})

sce <- do.call(cbind, sce_objects)
```

#Spillover Correction
Now we read in the spillover correction matrix from the spillover script. We overwrite
the data and apply common IMC transformations

```{r spillover correction}
rowData(sce)$channel_name <- paste0(panel$channel, "Di")
sce <- compCytof(sce, spillover, 
                 transform = TRUE, cofactor = 1,
                 isotope_list = isotope_list, 
                 overwrite = TRUE)
```

```{r}
objects <- read.csv(file = "/mnt/central_nas/projects/Pladioc/SRIMC_project/Zenodo/Figure_4/objects.csv", 
                    stringsAsFactors = FALSE)

objects$Object[objects$Image == "20240923_JWAB_Insitu_HRIMC_001.tiff"] <- paste0(objects$Object[objects$Image == "20240923_JWAB_Insitu_HRIMC_001.tiff"], "_1")
objects$Object[objects$Image == "20240923_JWAB_Insitu_HRIMC_002.tiff"] <- paste0(objects$Object[objects$Image == "20240923_JWAB_Insitu_HRIMC_002.tiff"], "_2")
objects$Object[objects$Image == "20240923_JWAB_Insitu_HRIMC_003.tiff"] <- paste0(objects$Object[objects$Image == "20240923_JWAB_Insitu_HRIMC_003.tiff"], "_3")

sce$Area <- objects$area[match(sce$cell, objects$Object)]
sce$major_axis <- objects$axis_major_length[match(sce$cell, objects$Object)]
sce$minor_axis <- objects$axis_minor_length[match(sce$cell, objects$Object)]
sce$eccentricity <- objects$eccentricity[match(sce$cell, objects$Object)]

```

```{r}

masks <- loadImages(path_to_masks, pattern = ".tiff", as.is = TRUE)
images <- loadImages(path_to_image, pattern = ".tiff")[1:3]

channelNames(images) <- rownames(sce)
images <- scaleImages(images, 2^16-1)

sce$image <- sub(".tiff", "", sce$image)
mcols(images)$image <- unique(sce$image)
mcols(masks)$image <- unique(sce$image)
sce$CellID <- c(1:length(sce$cell))

app <- cytoviewer(image = images, 
                  mask = masks, 
                  object = sce, 
                  img_id = "image", 
                  cell_id = "CellID")

if (interactive()) {
  shiny::runApp(app)
}

```

```{r saving}
saveRDS(sce, "/mnt/central_nas/projects/Pladioc/SRIMC_project/Zenodo/Figure_4/sce.RDS")
```


