---
title: "Untitled"
output: html_document
date: "2025-04-15"
editor_options: 
  chunk_output_type: console
---

```{r}
library(mclust)
library(circlize)
library(SingleCellExperiment)
library(CATALYST)
library(imcRtools)
library(Rphenograph)
library(dplyr)
library(ComplexHeatmap)
library(ggplot2)
library(scuttle)
library(scater)
```


```{r}
sce <- readRDS("/mnt/central_nas/projects/Pladioc/SRIMC_project/Zenodo/Figure_4/sce.RDS")

#Size exclusion of cells that are too big or too small
summary(sce$Area)
sum(sce$Area < 500)
sce$include <- sce$Area >= 500
sce <- sce[, which(sce$include == TRUE)]

sum(sce$Area > 8000)
sce$include <- sce$Area <= 8000
sce <- sce[, which(sce$include == TRUE)]

rownames(sce) <- c("cC3", "Xe", "panCK", "H3", "Vimentin", "MUC16", "Nestin", "GLUT1", "SMA", "GSTP1",
                   "p53", "CD20", "Ki67", "HSP70", "CD3", "Bcl2", "Erk", "ATP5A", "pH2AX", "pATM",
                   "HSP10", "Survivin", "TUBB3", "LRP", "Mesothelin", "CD45", "bCatenin",
                   "CD68", "H4K12Ac", "CAIX", "H3K4me2", "ERCC1", "CD31", "ECad", "Actin",
                   "pRb", "HSP27", "DNA1", "DNA2", "Pt195", "Pt196", "Pt198")

assay(sce, "scaled") <- t(scale(t(assay(sce, "exprs"))))

norm_counts <- t(apply(assay(sce, "counts"), 1, function(x)(x-min(x))/(quantile(x, 0.99)-min(x))))
norm_counts <- t(apply(norm_counts, 1, function(x) pmin(x, 1)))
assay(sce, "normalized", withDimnames = FALSE) <- norm_counts
```

```{r flowSOM clustering}

markers <- c("H3", "p53", "Ki67", "pH2AX", "pATM", "Survivin", "bCatenin",
             "H4K12Ac", "H3K4me2","pRb", "DNA1", "DNA2", "MUC16", "GLUT1",
             "GSTP1","HSP70", "ATP5A","HSP10", "TUBB3", "LRP", "Mesothelin",
             "ERCC1", "ECad","HSP27", "cC3")

assay(sce, "logcounts") <- assay(sce, "exprs")
assay(sce, "exprs") <- assay(sce, "normalized")

# Run FlowSOM and ConsensusClusterPlus clustering
set.seed(1255)
sce <- CATALYST::cluster(sce, features = markers, maxK = 30)
assay(sce, "exprs") <- assay(sce, "logcounts")

# Assess cluster stability
delta_area(sce)

# Assign clusters to sce object
set.seed(1234)
sce$som_cluster <- cluster_ids(sce, "meta12")

sce_mean <- aggregateAcrossCells(sce, ids = sce$som_cluster, statistics = "mean", use.assay.type = "counts")
assay(sce_mean, "exprs") <- asinh(assay(sce_mean, "counts"))
assay(sce_mean, "scaled") <- t(scale(t(assay(sce_mean, "exprs"))))

# Figure 4
my_palette <- colorRamp2(c(-2.5, 0, 2.5), c("#204a77", "white", "#CA3B43"))
Heatmap(assay(sce_mean, "scaled")[c("HSP10", "ATP5A"),],
        col = my_palette,
        column_names_rot = 90,
        cluster_rows = TRUE,
        cluster_columns = FALSE,
        border = TRUE, 
        column_names_side = "top",
        row_names_side = "left")
```

```{r Mitochondria detection}

# Mitochondria
sce <- buildSpatialGraph(sce, img_id = "image", type = "expansion",
                         threshold = 1, coords = c("Center_X", "Center_Y"))

sce <- patchDetection(sce, 
                      patch_cells = sce$som_cluster == "11",
                      img_id = "image",
                      coords = c("Center_X", "Center_Y"),
                      expand_by = 0,
                      min_patch_size = 1,
                      colPairName = "expansion_interaction_graph")

sce$patch <- "yes"
sce$patch[which(is.na(sce$patch_id))] <- "no"

mito <- as.data.frame(table(sce$patch_id, sce$cell))
mito <- mito[which(mito$Freq > 0),]

mito_size <- mito %>%
  dplyr::group_by(Var2) %>%
  dplyr::summarize(mean_freq = mean(Freq, na.rm = TRUE))

mito_freq <- as.data.frame(mito %>%
  dplyr::group_by(Var2) %>%
  dplyr::summarize(Count = n()))

```

```{r celltyping}

sce_mean <- aggregateAcrossCells(sce, ids = sce$cell, statistics = "mean", use.assay.type = "exprs")
sce_mean$mito_size <- mito_size$mean_freq[match(sce_mean$cell, mito_size$Var2)]
sce_mean$mito_num <- mito_freq$Count[match(sce_mean$cell, mito_freq$Var2)]
sce_mean$area <- sce$Area[match(sce_mean$cell, sce$cell)]
sce_mean$eccentricity <- sce$eccentricity[match(sce_mean$cell, sce$cell)]
markers_celltypes <- c("Vimentin", "CD45", "panCK", "SMA", "bCatenin", "ECad", "CD31")

# Clustering
mat <- t(assay(sce_mean, "exprs")[markers_celltypes,])

set.seed(230619)
out <- Rphenograph(mat, k = 20)
clusters <- factor(membership(out[[2]]))
sce_mean$clusters_k20 <- clusters

sce_clusters <- aggregateAcrossCells(sce_mean, ids = sce_mean$clusters_k20, statistics = "mean", use.assay.type = "exprs")
Heatmap(scale(t(assay(sce_clusters, "exprs")[c(markers_celltypes),])))

# Assigning cell types
clusters <- c("Other", "Tumor", "Endothelial", "Tumor", "Immune",
              "Fibroblast", "Tumor", "Tumor", "Tumor", "Tumor",
              "Fibroblast", "Fibroblast", "Tumor", "Endothelial", "Other",
              "Other", "Tumor", "Fibroblast", "Fibroblast", "Fibroblast",
              "Fibroblast", "Fibroblast", "Immune")
names(clusters) <- as.character(c(1:23))

sce_mean$celltype <- clusters[sce_mean$clusters_k20]

sce_clusters <- aggregateAcrossCells(sce_mean, ids = sce_mean$celltype, statistics = "mean", use.assay.type = "exprs")
meta <- aggregate(colData(sce_mean), by = list(sce_mean$celltype), FUN = "mean", na.rm = TRUE)

row_anno <- rowAnnotation(area = meta$area,
                          eccentricity = meta$eccentricity,
                          mito_num = meta$mito_num,
                          mito_size = meta$mito_size,
                          celltype = meta$celltype)

markers_plot <- c("panCK", "Vimentin", "GLUT1", "SMA", "CD20", "Ki67", "CD3", "CD45", "bCatenin", "CD31", "ECad")
my_palette <- colorRamp2(c(-2, 0, 2), c("#204a77", "white", "#CA3B43"))
Heatmap(scale(t(assay(sce_clusters, "exprs")[c(markers_plot),which(colnames(sce_clusters) != "Other")])),
        col = my_palette)

```

```{r comparing cell types}

sce_mean$mito_num_corrected <- sce_mean$mito_num/sce_mean$area

ggcells(sce_mean[,which(sce_mean$celltype %in% c("Tumor", "Immune", "Fibroblast"))], 
        aes(x = celltype, y = mito_num_corrected), assay.type = "exprs") +
  geom_boxplot(fill = "lightgrey") +
  theme_minimal() +
  ylim(c(0,0.1)) +
    theme(
      panel.grid.major = element_blank(),   
      panel.grid.minor = element_blank(),   
      panel.border = element_rect(colour = "black", fill = NA, size = 0.3),  
      plot.background = element_blank()     
    )

tumor_info <- aggregate(sce_mean$mito_num_corrected[sce_mean$celltype == "Tumor"], 
                        by = list(sce_mean$image[sce_mean$celltype == "Tumor"]), FUN = "mean", na.rm = TRUE)
immune_info <- aggregate(sce_mean$mito_num_corrected[sce_mean$celltype == "Immune"], 
                        by = list(sce_mean$image[sce_mean$celltype == "Immune"]), FUN = "mean", na.rm = TRUE)
fibro_info <- aggregate(sce_mean$mito_num_corrected[sce_mean$celltype == "Fibroblast"], 
                        by = list(sce_mean$image[sce_mean$celltype == "Fibroblast"]), FUN = "mean", na.rm = TRUE)
t.test(sce_mean$mito_num_corrected[sce_mean$celltype == "Tumor"], sce_mean$mito_num_corrected[sce_mean$celltype == "Immune"])
t.test(sce_mean$mito_num_corrected[sce_mean$celltype == "Tumor"], sce_mean$mito_num_corrected[sce_mean$celltype == "Fibroblast"])

t.test(tumor_info$x, c(immune_info$x, NA), paired = TRUE)
t.test(tumor_info$x, fibro_info$x, paired = TRUE)

ggcells(sce_mean[,which(sce_mean$celltype %in% c("Tumor", "Immune", "Fibroblast"))], 
        aes(x = celltype, y = mito_size), assay.type = "exprs") +
  geom_boxplot(fill = "lightgrey") +
  theme_minimal() +
  ylim(c(0,15)) +
    theme(
      panel.grid.major = element_blank(),   
      panel.grid.minor = element_blank(),   
      panel.border = element_rect(colour = "black", fill = NA, size = 0.3),  
      plot.background = element_blank()     
    )

tumor_info <- aggregate(sce_mean$mito_size[sce_mean$celltype == "Tumor"], 
                        by = list(sce_mean$image[sce_mean$celltype == "Tumor"]), FUN = "mean", na.rm = TRUE)
immune_info <- aggregate(sce_mean$mito_size[sce_mean$celltype == "Immune"], 
                        by = list(sce_mean$image[sce_mean$celltype == "Immune"]), FUN = "mean", na.rm = TRUE)
fibro_info <- aggregate(sce_mean$mito_size[sce_mean$celltype == "Fibroblast"], 
                        by = list(sce_mean$image[sce_mean$celltype == "Fibroblast"]), FUN = "mean", na.rm = TRUE)

t.test(sce_mean$mito_size[sce_mean$celltype == "Tumor"], sce_mean$mito_size[sce_mean$celltype == "Immune"])
t.test(sce_mean$mito_size[sce_mean$celltype == "Tumor"], sce_mean$mito_size[sce_mean$celltype == "Fibroblast"])

t.test(tumor_info$x, c(immune_info$x, NA), paired = TRUE)
t.test(tumor_info$x, fibro_info$x, paired = TRUE)


```


```{r comparing normoxic and hypoxic tumor cells}

mcl.model <- densityMclust(as.numeric(assay(sce_mean, "exprs")["CAIX", sce_mean$celltype == "Tumor"]), 2)
sce_mean$hypoxic <- NA
sce_mean$hypoxic[sce_mean$celltype == "Tumor"] <- as.character(mcl.model$classification)

ggcells(sce_mean[,which(sce_mean$celltype %in% c("Tumor"))], 
        aes(x = hypoxic, y = GLUT1), assay.type = "exprs") +
  geom_boxplot(fill = "lightgrey") +
  theme_minimal() +
  ylim(c(0,0.1))+
    theme(
      panel.grid.major = element_blank(),   
      panel.grid.minor = element_blank(),   
      panel.border = element_rect(colour = "black", fill = NA, size = 0.3),  
      plot.background = element_blank()     
    ) 

normoxic_info <- aggregate(assay(sce_mean, "exprs")["GLUT1",which(sce_mean$hypoxic == "1")], 
                        by = list(sce_mean$image[which(sce_mean$hypoxic == "1")]), FUN = "median", na.rm = TRUE)
hypoxic_info <- aggregate(assay(sce_mean, "exprs")["GLUT1",which(sce_mean$hypoxic == "2")], 
                        by = list(sce_mean$image[which(sce_mean$hypoxic == "2")]), FUN = "median", na.rm = TRUE)
t.test(assay(sce_mean, "exprs")["GLUT1",which(sce_mean$hypoxic == "1")], assay(sce_mean, "exprs")["GLUT1",which(sce_mean$hypoxic == "2")])
t.test(normoxic_info$x, hypoxic_info$x, paired = TRUE)

ggcells(sce_mean[,which(sce_mean$celltype %in% c("Tumor"))], 
        aes(x = hypoxic, y = mito_size), assay.type = "exprs") +
  geom_boxplot(fill = "lightgrey") +
  theme_minimal() +
  ylim(c(0,15))+
    theme(
      panel.grid.major = element_blank(),   
      panel.grid.minor = element_blank(),   
      panel.border = element_rect(colour = "black", fill = NA, size = 0.3),  
      plot.background = element_blank()     
    ) 
normoxic_info <- aggregate(sce_mean$mito_size[which(sce_mean$hypoxic == "1")], 
                        by = list(sce_mean$image[which(sce_mean$hypoxic == "1")]), FUN = "mean", na.rm = TRUE)
hypoxic_info <- aggregate(sce_mean$mito_size[which(sce_mean$hypoxic == "2")], 
                        by = list(sce_mean$image[which(sce_mean$hypoxic == "2")]), FUN = "mean", na.rm = TRUE)
t.test(sce_mean$mito_size[sce_mean$hypoxic == "2"], sce_mean$mito_size[sce_mean$hypoxic == "1"])
t.test(normoxic_info$x, hypoxic_info$x, paired = TRUE)

ggcells(sce_mean[,which(sce_mean$celltype %in% c("Tumor"))], 
        aes(x = hypoxic, y = mito_num_corrected), assay.type = "exprs") +
  geom_boxplot(fill = "lightgrey") +
  theme_minimal() +
  ylim(c(0,0.1))+
    theme(
      panel.grid.major = element_blank(),   
      panel.grid.minor = element_blank(),   
      panel.border = element_rect(colour = "black", fill = NA, size = 0.3),  
      plot.background = element_blank()     
    ) 

normoxic_info <- aggregate(sce_mean$mito_num_corrected[which(sce_mean$hypoxic == "1")], 
                        by = list(sce_mean$image[which(sce_mean$hypoxic == "1")]), FUN = "mean", na.rm = TRUE)
hypoxic_info <- aggregate(sce_mean$mito_num_corrected[which(sce_mean$hypoxic == "2")], 
                        by = list(sce_mean$image[which(sce_mean$hypoxic == "2")]), FUN = "mean", na.rm = TRUE)
t.test(sce_mean$mito_num_corrected[sce_mean$hypoxic == "2"], sce_mean$mito_num_corrected[sce_mean$hypoxic == "1"])
t.test(normoxic_info$x, hypoxic_info$x, paired = TRUE)

```

