---
title: "Untitled"
output: html_document
date: "2025-03-26"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(cytomapper)
library(imager)
```


```{r signal to noise ratio}

images <- loadImages("/mnt/central_nas/projects/Pladioc/SRIMC_project/Revisions/1um_real_convolved/images_analysis/")

channelNames(images) <- c("MPO", "H3", "CD11c", "Xe134", "ECad", "CCR7", "Vimentin",
                          "HLADR", "CD4_2", "SMA", "CD11b", "CD20", "CD56",
                          "Decorin", "CD3", "DC_LAMP", "ATP5A", "Periostin", "H3K27me2", "HSP10", 
                          "CD8", "CD45", "FOXP3_2", "CD68", "Ki67", "CD8_2", "FOXP3",
                          "IRF4", "CD4", "CD31", "CXCL12", "DNA1", "DNA2", "CD15")

# Store patient and image level information in elementMetadata
mcols(images) <- DataFrame(image = names(images))

# Align images

cur <- lapply(names(images), function(x){
    img <- images[[x]]
    mat <- apply(img, 3, function(ch){
        # Otsu threshold
        thres <- otsu(ch, range = c(min(ch), max(ch)), levels = 260000)

        snr <- mean(ch[ch > thres]) / mean(ch[ch <= thres])
        ps <- mean(ch[ch > thres])
        ts <- sum(ch[ch > thres])
        
        return(c(snr = snr, ps = ps, ts = ts))
    })
    t(mat) %>% as.data.frame() %>% 
        mutate(image = x,
               marker = colnames(mat)) %>% 
        pivot_longer(cols = c(snr, ps, ts))
})

cur_snr <- do.call(rbind, cur)
cur_snr$resolution <- c(rep("classic IMC - HR-IMC (333nm)", 102), rep("classic IMC - HR-IMC (500nm)", 102), 
                        rep("HR-IMC (333nm)", 102), rep("HR-IMC (500nm)", 102),
                        rep("conv_HR-IMC (333nm)", 102), rep("conv_HR-IMC (500nm)", 102))

data <- cur_snr %>% 
    pivot_wider(names_from = name, values_from = value) %>%
    pivot_longer(cols = c(snr, ps))

data <- data %>% 
    dplyr::group_by(marker, name, resolution) %>%
    dplyr::summarize(log_mean = log2(mean(value))) %>%
    pivot_wider(names_from = name, values_from = log_mean)

markers <- c("H3", "CD11c", "ECad", "CCR7", "Vimentin",
             "HLADR", "SMA", "CD11b", "CD20", "CD56",
             "CD3", "DC_LAMP", "ATP5A", "H3K27me2", "HSP10", 
             "CD8", "CD45", "CD68", "Ki67", "FOXP3",
             "IRF4", "CD4", "CD31", "DNA1", "DNA2", "CD15")

input <- data[which(data$resolution %in% c("conv_HR-IMC (333nm)", "classic IMC - HR-IMC (333nm)") & 
                      data$marker %in% markers),]
input$resolution <- factor(input$resolution, levels = unique(input$resolution))
  
ggplot(input, aes(ps, snr)) +
    geom_point(aes(col = resolution)) +
    geom_label(aes(label = marker, col = resolution)) +
  #scale_color_manual(values = c("#33608C", "#DD708E", "#EA7246", "#F5B35E")) +
    ylab("Signal-to-noise ratio [log2]") +
    xlab("Signal intensity [log2]") +
  theme(panel.grid = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, size = 1),
        panel.background = element_rect(fill = "white")) 

input$marker <- factor(input$marker, levels = unique(input$marker[order(input$snr, decreasing = FALSE)]))
ggplot(as.data.frame(input), aes(x = marker, y = snr, col = resolution, group = marker)) +
  geom_point(size = 3, alpha = 0.7) +
  scale_color_manual(values = c("grey", "#204a77")) +
  theme_minimal() +  
  ylab("SNR [log2]") +
  geom_line(color = "grey", linetype = "dotted") +
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.border = element_rect(colour = "black", fill = NA, size = 0.3),
      plot.background = element_blank(),
      axis.text.x = element_text(angle = 90, hjust = 1)
    )

input$marker <- factor(input$marker, levels = unique(input$marker[order(input$ps, decreasing = FALSE)]))
ggplot(as.data.frame(input), aes(x = marker, y = ps, col = resolution, group = marker)) +
  geom_point(size = 3, alpha = 0.7) +
  scale_color_manual(values = c("grey","#DD708E")) +
  theme_minimal() +  
  ylab("Signal intensity") +
  geom_line(color = "grey", linetype = "dotted") +
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.border = element_rect(colour = "black", fill = NA, size = 0.3),
      plot.background = element_blank(),
      axis.text.x = element_text(angle = 90, hjust = 1)
    )

```

```{r correlation between convolved and real data}
images <- loadImages("/mnt/central_nas/projects/Pladioc/SRIMC_project/Revisions/1um_real_convolved/images_analysis/")

channelNames(images) <- c("MPO", "H3", "CD11c", "Xe134", "ECad", "CCR7", "Vimentin",
                          "HLADR", "CD4_2", "SMA", "CD11b", "CD20", "CD56",
                          "Decorin", "CD3", "DC_LAMP", "ATP5A", "Periostin", "H3K27me2", "HSP10", 
                          "CD8", "CD45", "FOXP3_2", "CD68", "Ki67", "CD8_2", "FOXP3",
                          "IRF4", "CD4", "CD31", "CXCL12", "DNA1", "DNA2", "CD15")

# Store patient and image level information in elementMetadata
mcols(images) <- DataFrame(image = names(images))
affine_matrix <- read.csv("/mnt/central_nas/projects/Pladioc/SRIMC_project/Revisions/1um_real_convolved/transformation.txt", header = FALSE)

## GENERATE the convolved-IMC
image_matrix <- imageData(images[[5]])
pixel_coordinates <- expand.grid(row = 1:nrow(image_matrix), col = 1:ncol(image_matrix))
pixel_DNA <- as.vector(image_matrix[,,12])
pixel_SMA <- as.vector(image_matrix[,,10])
pixel_CD11b <- as.vector(image_matrix[,,14])

sce_333 <- SingleCellExperiment(assays = list(counts = rbind(pixel_DNA, pixel_SMA, pixel_CD11b)))
rownames(sce_333) <- c("CD20", "SMA", "Decorin")

sce_333$Center_X <- pixel_coordinates$col
sce_333$Center_Y <- pixel_coordinates$row
sce_333$image <- "tiff_IMC_convolved"

assay(sce_333, "exprs") <- asinh(assay(sce_333, "counts"))
assay(sce_333, "scaled") <- t(scale(t(assay(sce_333, "exprs"))))
cell_norm_counts <- t(apply(assay(sce_333, "counts"), 1, function(x)(x-min(x))/(quantile(x, 0.99)-min(x))))
cell_norm_counts <- t(apply(cell_norm_counts, 1, function(x) pmin(x, 1)))
assay(sce_333, "normalized", withDimnames = FALSE) <- cell_norm_counts

coords_matrix <- cbind(sce_333$Center_X, sce_333$Center_Y, 1)
sce_333$match <- paste0(sce_333$Center_X, "_", sce_333$Center_Y)

## GENERATE the classic-IMC
image_matrix <- imageData(images[[1]])
pixel_coordinates <- expand.grid(row = 1:nrow(image_matrix), col = 1:ncol(image_matrix))
pixel_DNA <- as.vector(image_matrix[,,12])
pixel_SMA <- as.vector(image_matrix[,,10])
pixel_CD11b <- as.vector(image_matrix[,,14])

sce_real <- SingleCellExperiment(assays = list(counts = rbind(pixel_DNA, pixel_SMA, pixel_CD11b)))
rownames(sce_real) <- c("CD20", "SMA", "Decorin")

sce_real$Center_X <- pixel_coordinates$col
sce_real$Center_Y <- pixel_coordinates$row
sce_real$image <- "tiff_IMC_real"

assay(sce_real, "exprs") <- asinh(assay(sce_real, "counts"))
assay(sce_real, "scaled") <- t(scale(t(assay(sce_real, "exprs"))))
cell_norm_counts <- t(apply(assay(sce_real, "counts"), 1, function(x)(x-min(x))/(quantile(x, 0.99)-min(x))))
cell_norm_counts <- t(apply(cell_norm_counts, 1, function(x) pmin(x, 1)))
assay(sce_real, "normalized", withDimnames = FALSE) <- cell_norm_counts

coords_matrix <- cbind(sce_real$Center_X, sce_real$Center_Y, 1)
transformed_coords <- coords_matrix %*% t(affine_matrix)

sce_real$Center_X_trans <-  as.integer(transformed_coords[, 1])
sce_real$Center_Y_trans <- as.integer(transformed_coords[, 2])

sce_real$match <- paste0(sce_real$Center_X_trans, "_", sce_real$Center_Y_trans)


```

```{r plotting}

input_333 <- sce_333[,which(sce_333$Center_Y <= 505 &
                            sce_333$Center_Y >= 100 &
                            sce_333$Center_X <= 450 & 
                            sce_333$Center_X >= 50)]

plotSpatial(input_333, img_id = "image",
            coords = c("Center_X", "Center_Y"),
            node_color_by = "SMA",
            assay_type = "exprs",
            node_size_fix = 0.1)

input_real <- sce_real[,which(sce_real$Center_Y_trans <= 505 &
                              sce_real$Center_Y_trans >= 100 &
                              sce_real$Center_X_trans <= 450 & 
                              sce_real$Center_X_trans >= 50)]

plotSpatial(input_real, img_id = "image",
            coords = c("Center_X_trans", "Center_Y_trans"),
            node_color_by = "SMA",
            assay_type = "exprs",
            node_size_fix = 0.1)

```


```{r correlation demonstration for SMA}

input_classic <- sce_real
input_333 <- sce_333

bin_size <- 8

# Create binned coordinates
input_333$bin_x <- ceiling(input_333$Center_X / bin_size) * bin_size
input_333$bin_y <- ceiling(input_333$Center_Y / bin_size) * bin_size

input_classic$bin_x <- ceiling(input_classic$Center_X_trans / bin_size) * bin_size
input_classic$bin_y <- ceiling(input_classic$Center_Y_trans / bin_size) * bin_size

#SMA
imc_333_binned <- data.frame(expr = assay(input_333, "counts")["SMA", ],
                         bin_x = input_333$bin_x,
                         bin_y = input_333$bin_y) |>
  dplyr::group_by(bin_x, bin_y) |>
  dplyr::summarise(DNA = mean(expr, na.rm = TRUE), .groups = "drop")

imc_classic_binned <- data.frame(expr = assay(input_classic, "counts")["SMA", ],
                         bin_x = input_classic$bin_x,
                         bin_y = input_classic$bin_y) |>
  dplyr::group_by(bin_x, bin_y) |>
  dplyr::summarise(DNA = mean(expr, na.rm = TRUE), .groups = "drop")

binned_merged_classic <- inner_join(imc_333_binned, imc_classic_binned, by = c("bin_x", "bin_y"),
                             suffix = c("_convolved", "_classic"))

cor(binned_merged_classic$DNA_convolved, binned_merged_classic$DNA_classic, use = "complete.obs")

ggplot(binned_merged_classic, aes(x = asinh(DNA_convolved), y = asinh(DNA_classic))) +
  geom_point(col = "grey", alpha = 0.5, size = 0.5) +
  geom_smooth(method = "lm", col = "darkorange", fill = alpha("darkorange", 0.5)) +
  theme_minimal() +  
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.border = element_rect(colour = "black", fill = NA, size = 0.3),
      plot.background = element_blank(),
      axis.text.x = element_text(angle = 90, hjust = 1)
    )

```





