---
title: "Untitled"
output: html_document
date: "2025-04-02"
editor_options: 
  chunk_output_type: console
---

```{r}
library(cytomapper)
library(EBImage)
library(ggplot2)
library(tidyr)
library(dplyr)
```


```{r}

images <- loadImages("/mnt/central_nas/projects/Pladioc/SRIMC_project/Revisions/mcd/20250319_JWAB_TMA_matchedHE_SHRIMP/img/")

channelNames(images) <- c("MPO", "H3", "CD11c", "Xe134", "ECad", "CCR7", "Vimentin",
                          "HLADR", "CD4_2", "SMA", "CD11b", "CD20", "CD56",
                          "Decorin", "CD3", "DC_LAMP", "ATP5A", "Periostin", "H3K27me2", "HSP10", 
                          "CD8", "CD45", "FOXP3_2", "CD68", "Ki67", "CD8_2", "FOXP3",
                          "IRF4", "CD4", "CD31", "CXCL12", "DNA1", "DNA2", "CD15")

images <- lapply(images, function(img) img[25:75, 50:100, ])

names(images) <- c("-10dB_pass_1", "-10dB_pass_9", "-10dB_pass_2", "-10dB_pass_3", "-10dB_pass_4", "-10dB_pass_5",
                   "-10dB_pass_x", "-10dB_pass_6", "-10dB_pass_7", "-10dB_pass_8", "-10dB_pass_10",
                   "-2dB_pass_1", "-2dB_pass_10", "-2dB_pass_2", "-2dB_pass_3", "-2dB_pass_4", "-2dB_pass_5",
                   "-2dB_pass_6", "-2dB_pass_7", "-2dB_pass_8", "-2dB_pass_9", 
                   "-4dB_pass_10", "-4dB_pass_2", "-4dB_pass_3", "-4dB_pass_4", "-4dB_pass_5", "-4dB_pass_6",
                   "-4dB_pass_7", "-4dB_pass_8", "-4dB_pass_9", "-4dB_pass_1",
                   "-6dB_pass_1", "-6dB_pass_10", "-6dB_pass_2", "-6dB_pass_3", "-6dB_pass_4", "-6dB_pass_5",
                   "-6dB_pass_6", "-6dB_pass_7", "-6dB_pass_8", "-6dB_pass_9",
                   "-8dB_pass_1", "-8dB_pass_10", "-8dB_pass_2", "-8dB_pass_3", "-8dB_pass_4", "-8dB_pass_5",
                   "-8dB_pass_6", "-8dB_pass_7", "-8dB_pass_8", "-8dB_pass_9",
                   "0dB_pass_1", "0dB_pass_2", "0dB_pass_3", "0dB_pass_4", "0dB_pass_5")

cors_10 <- c(1,
          cor(c(imageData(images[["-10dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-10dB_pass_2"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-10dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-10dB_pass_3"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-10dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-10dB_pass_4"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-10dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-10dB_pass_5"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-10dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-10dB_pass_6"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-10dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-10dB_pass_7"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-10dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-10dB_pass_8"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-10dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-10dB_pass_9"]])[,,"DNA1"]), method = "spearman")
          )

cors_10_cons <- c(cor(c(imageData(images[["-10dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-10dB_pass_2"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-10dB_pass_2"]])[,,"DNA1"]), c(imageData(images[["-10dB_pass_3"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-10dB_pass_3"]])[,,"DNA1"]), c(imageData(images[["-10dB_pass_4"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-10dB_pass_4"]])[,,"DNA1"]), c(imageData(images[["-10dB_pass_5"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-10dB_pass_5"]])[,,"DNA1"]), c(imageData(images[["-10dB_pass_6"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-10dB_pass_6"]])[,,"DNA1"]), c(imageData(images[["-10dB_pass_7"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-10dB_pass_7"]])[,,"DNA1"]), c(imageData(images[["-10dB_pass_8"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-10dB_pass_8"]])[,,"DNA1"]), c(imageData(images[["-10dB_pass_9"]])[,,"DNA1"]), method = "spearman")
          )

cors_8 <- c(1,
          cor(c(imageData(images[["-8dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-8dB_pass_2"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-8dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-8dB_pass_3"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-8dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-8dB_pass_4"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-8dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-8dB_pass_5"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-8dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-8dB_pass_6"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-8dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-8dB_pass_7"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-8dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-8dB_pass_8"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-8dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-8dB_pass_9"]])[,,"DNA1"]), method = "spearman")
          )

cors_6 <- c(1,
          cor(c(imageData(images[["-6dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-6dB_pass_2"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-6dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-6dB_pass_3"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-6dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-6dB_pass_4"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-6dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-6dB_pass_5"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-6dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-6dB_pass_6"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-6dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-6dB_pass_7"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-6dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-6dB_pass_8"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-6dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-6dB_pass_9"]])[,,"DNA1"]), method = "spearman")
          )

cors_4 <- c(1,
          cor(c(imageData(images[["-4dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-4dB_pass_2"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-4dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-4dB_pass_3"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-4dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-4dB_pass_4"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-4dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-4dB_pass_5"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-4dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-4dB_pass_6"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-4dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-4dB_pass_7"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-4dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-4dB_pass_8"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-4dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-4dB_pass_9"]])[,,"DNA1"]), method = "spearman")
          )

cors_2 <- c(1,
          cor(c(imageData(images[["-2dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-2dB_pass_2"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-2dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-2dB_pass_3"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-2dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-2dB_pass_4"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-2dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-2dB_pass_5"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-2dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-2dB_pass_6"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-2dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-2dB_pass_7"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-2dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-2dB_pass_8"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["-2dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["-2dB_pass_9"]])[,,"DNA1"]), method = "spearman")
          )

cors_0 <- c(1,
          cor(c(imageData(images[["0dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["0dB_pass_2"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["0dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["0dB_pass_3"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["0dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["0dB_pass_4"]])[,,"DNA1"]), method = "spearman"),
          cor(c(imageData(images[["0dB_pass_1"]])[,,"DNA1"]), c(imageData(images[["0dB_pass_5"]])[,,"DNA1"]), method = "spearman")
          )


data <- data.frame(pass = c(2:9),
                   cor = cors_10_cons)
ggplot(data, aes(pass, cor)) +
  geom_point(shape=21, size = 3, alpha = 0.7, fill = "#33608C", col = "white") +
  ylim(c(0,1))+
  ylab("Correlation")+
  xlab("Pass Number")+
  geom_smooth(data = data[1:7,], method = "lm", se = TRUE, col = "grey") +
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1),
        panel.background = element_blank(),
        panel.grid.minor = element_line(colour="grey95", size=0.5),
        text = element_text(size = 15))

data <- data.frame(pass = c(1:9),
                   cor = cors_10)
ggplot(data, aes(pass, cor)) +
  geom_point(shape=21, size = 3, alpha = 0.7, fill = "#33608C", col = "white") +
  ylim(c(0,1))+
  ylab("Correlation")+
  xlab("Pass Number")+
  geom_smooth(method = "lm", formula = y ~ exp(-0.3*x), se = TRUE, col = "grey") +
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1),
        panel.background = element_blank(),
        panel.grid.minor = element_line(colour="grey95", size=0.5),
        text = element_text(size = 15))




```

