---
title: "Untitled"
output: html_document
date: "2025-04-26"
editor_options: 
  chunk_output_type: console
---

```{r}

tiff_deconvolved <- loadImages("~/mnt/central_nas/projects/Pladioc/SRIMC_project/FINAL/Extended_Data_1/SMA_fibres/deconvolved/IF_GLUT1_SMA_FFPE_lung_333.tiff")
tiff_raw <- loadImages("~/mnt/central_nas/projects/Pladioc/SRIMC_project/FINAL/Extended_Data_1/SMA_fibres/raw/IF_GLUT1_SMA_FFPE_lung_333.tiff")

## Generate the deconvolved IMC
image_matrix <- imageData(tiff_deconvolved[[1]])
pixel_coordinates <- expand.grid(row = 1:nrow(image_matrix), col = 1:ncol(image_matrix))
pixel_GLUT1 <- as.vector(image_matrix[,,2])
pixel_SMA <- as.vector(image_matrix[,,3])
pixel_DNA <- as.vector(image_matrix[,,5])

sce_deconvolved <- SingleCellExperiment(assays = list(counts = rbind(pixel_GLUT1, pixel_SMA, pixel_DNA)))
rownames(sce_deconvolved) <- c("GLUT1", "SMA", "DNA")

sce_deconvolved$Center_X <- pixel_coordinates$col
sce_deconvolved$Center_Y <- pixel_coordinates$row
sce_deconvolved$image <- "deconvolved"

assay(sce_deconvolved, "exprs") <- asinh(assay(sce_deconvolved, "counts"))
assay(sce_deconvolved, "scaled") <- t(scale(t(assay(sce_deconvolved, "exprs"))))
cell_norm_counts <- t(apply(assay(sce_deconvolved, "counts"), 1, function(x)(x-min(x))/(quantile(x, 0.99)-min(x))))
cell_norm_counts <- t(apply(cell_norm_counts, 1, function(x) pmin(x, 1)))
assay(sce_deconvolved, "normalized", withDimnames = FALSE) <- cell_norm_counts

## Generate the convolved IMC
imageData(tiff_raw[[1]]) <- imageData(tiff_raw[[1]][4:906,4:906,])
image <- EBImage::resize(tiff_raw[[1]], w = 301, h = 301)
tiff_convolved <- image[rep(1:301, each = 3), 
                        rep(1:301, each = 3), 
                        , drop = FALSE]
image_matrix <- imageData(tiff_convolved)
pixel_coordinates <- expand.grid(row = 1:nrow(image_matrix), col = 1:ncol(image_matrix))
pixel_GLUT1 <- as.vector(image_matrix[,,2])
pixel_SMA <- as.vector(image_matrix[,,3])
pixel_DNA <- as.vector(image_matrix[,,5])

sce_convolved <- SingleCellExperiment(assays = list(counts = rbind(pixel_GLUT1, pixel_SMA, pixel_DNA)))
rownames(sce_convolved) <- c("GLUT1", "SMA", "DNA")

sce_convolved$Center_X <- pixel_coordinates$col
sce_convolved$Center_Y <- pixel_coordinates$row
sce_convolved$image <- "convolved"

assay(sce_convolved, "exprs") <- asinh(assay(sce_convolved, "counts"))
assay(sce_convolved, "scaled") <- t(scale(t(assay(sce_convolved, "exprs"))))
cell_norm_counts <- t(apply(assay(sce_convolved, "counts"), 1, function(x)(x-min(x))/(quantile(x, 0.99)-min(x))))
cell_norm_counts <- t(apply(cell_norm_counts, 1, function(x) pmin(x, 1)))
assay(sce_convolved, "normalized", withDimnames = FALSE) <- cell_norm_counts

```

```{r ROI 1}

plotSpatial(sce_convolved[,which(sce_convolved$Center_X > 400 & sce_convolved$Center_X < 550 &
                                      sce_convolved$Center_Y > 500 & sce_convolved$Center_Y < 650)],
            img_id = "image",
            coords = c("Center_X", "Center_Y"),
            node_color_by = "SMA",
            node_shape_fix = 15,
            assay_type = "exprs",
            node_size_fix = 2.5) +
  scale_color_gradientn(colors = magma(256), limits = c(0,7))

plotSpatial(sce_deconvolved[,which(sce_deconvolved$Center_X > 400 & sce_deconvolved$Center_X < 550 &
                                      sce_deconvolved$Center_Y > 500 & sce_deconvolved$Center_Y < 650)], 
            img_id = "image",
            coords = c("Center_X", "Center_Y"),
            node_color_by = "SMA",
            assay_type = "exprs",
            node_shape_fix = 15,
            node_size_fix = 2.5) +
  scale_color_gradientn(colors = magma(256))

######

plotSpatial(sce_deconvolved[,which(sce_deconvolved$Center_X > 470 & sce_deconvolved$Center_X < 530 &
                                      sce_deconvolved$Center_Y > 560 & sce_deconvolved$Center_Y < 570)], 
            img_id = "image",
            coords = c("Center_X", "Center_Y"),
            node_color_by = "SMA",
            assay_type = "exprs",
            node_shape_fix = 15,
            node_size_fix = 3) +
  scale_color_gradientn(colors = magma(256))

plotSpatial(sce_convolved[,which(sce_convolved$Center_X > 470 & sce_convolved$Center_X < 530 &
                                      sce_convolved$Center_Y > 560 & sce_convolved$Center_Y < 570)], 
            img_id = "image",
            coords = c("Center_X", "Center_Y"),
            node_color_by = "SMA",
            assay_type = "exprs",
            node_shape_fix = 15,
            node_size_fix = 3) +
  scale_color_gradientn(colors = magma(256), limits = c(0,7))

data <- cbind(sce_deconvolved, sce_convolved)
ggcells(data[,which(data$Center_X > 470 & data$Center_X < 530 &
                                 data$Center_Y == 566)], 
        aes(x = Center_X, y = SMA, col = image), assay.type = "normalized") +
  geom_smooth(se = FALSE, method = "loess", span = 0.05, size = 0.5) +
  theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.border = element_rect(colour = "black", fill = NA, size = 0.3),
      panel.background = element_rect(colour = "white", fill = "white"),
      axis.text.x = element_text(angle = 90, hjust = 1)
    ) +
  scale_color_manual(values = c("grey", "#9A68A4"))

```

```{r ROI 2}

plotSpatial(sce_convolved[,which(sce_convolved$Center_X > 300 & sce_convolved$Center_X < 450 &
                                      sce_convolved$Center_Y > 270 & sce_convolved$Center_Y < 420)],
            img_id = "image",
            coords = c("Center_X", "Center_Y"),
            node_color_by = "SMA",
            node_shape_fix = 15,
            assay_type = "exprs",
            node_size_fix = 2.5) +
  scale_color_gradientn(colors = magma(256), limits = c(0,7))

plotSpatial(sce_deconvolved[,which(sce_deconvolved$Center_X > 300 & sce_deconvolved$Center_X < 450 &
                                      sce_deconvolved$Center_Y > 270 & sce_deconvolved$Center_Y < 420)], 
            img_id = "image",
            coords = c("Center_X", "Center_Y"),
            node_color_by = "SMA",
            assay_type = "exprs",
            node_shape_fix = 15,
            node_size_fix = 2.5) +
  scale_color_gradientn(colors = magma(256))


#####
plotSpatial(sce_deconvolved[,which(sce_deconvolved$Center_X > 355 & sce_deconvolved$Center_X < 430 &
                                      sce_deconvolved$Center_Y > 315 & sce_deconvolved$Center_Y < 325)], 
            img_id = "image",
            coords = c("Center_X", "Center_Y"),
            node_color_by = "SMA",
            assay_type = "exprs",
            node_shape_fix = 15,
            node_size_fix = 3) +
  scale_color_gradientn(colors = magma(256))

plotSpatial(sce_convolved[,which(sce_convolved$Center_X > 355 & sce_convolved$Center_X < 430 &
                                      sce_convolved$Center_Y > 315 & sce_convolved$Center_Y < 325)], 
            img_id = "image",
            coords = c("Center_X", "Center_Y"),
            node_color_by = "SMA",
            assay_type = "exprs",
            node_shape_fix = 15,
            node_size_fix = 3) +
  scale_color_gradientn(colors = magma(256), limits = c(0,7))

data <- cbind(sce_deconvolved, sce_convolved)
ggcells(data[,which(data$Center_X > 355 & data$Center_X < 430 &
                                 data$Center_Y == 319)], 
        aes(x = Center_X, y = SMA, col = image), assay.type = "normalized") +
  geom_smooth(se = FALSE, method = "loess", span = 0.05, size = 0.5) +
  theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.border = element_rect(colour = "black", fill = NA, size = 0.3),
      panel.background = element_rect(colour = "white", fill = "white"),
      axis.text.x = element_text(angle = 90, hjust = 1)
    ) +
  scale_color_manual(values = c("grey", "#9A68A4"))

```


